baseURL = "http://example.org/"
languageCode = "en-us"
title = "astrology"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
googleAnalytics = ""
enableRobotsTXT = true

[params]
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/jocelynr58"
  instagram = "https://www.instagram.com/joce.rk/"
  youtube = ""
  github = ""
  linkedin = ""
  background_color_class = "bg-navy"
  featured_image = "https://78.media.tumblr.com/75908fceb2c4a99a8312ecf69880c2b7/tumblr_p4jbh1sL4I1w8qokno1_500.gif"
  recent_posts_number = 1
  custom_css = ["/custom.css"]